### PR TITLE
Change handling of webaudio radius & volume

### LINKED ISSUE #13: Last update (#12) causes streams to be too quiet & range does not work
The last update (#12) causes streams to have very a low volume (the volume does change when webaudio:volume() is used, but the stream is very quiet), and the audio can be heard regardless of distance from E2 to player. Setting the range seems to make no difference to this.

### PR DESCRIPTION
**Pull request by Vurv78**
Fixes #13, also made the maximum radius and volume settings much more relaxed at 3x volume and 10,000 source units distance radius. If you want it lower, just set your server or client's convars.

### CODE REVIEW

**Comment by Vurv78** [comment]
Can you test if this works fine for you? @RanchTheDeer 
I buffed the default convars as well since the server and client can always change the settings themselves

**Comment by RanchTheDeer** [comment]
For me, these changes cause the stream to play with no volume whatsoever
With a little debugging, `print(stream.volume * ( 1 - math_min(dist_to_stream / stream.radius, 1)))` always seems to return a value of 0 despite the stream volume being set to 100 and the max volume being at 200

**Comment by Vurv78** [comment]
You're most likely using ``setPos`` at the same tick of ``setParent``, which results in the stream being parented to the object local to the stream's set position. This is expected behavior

**Comment by Vurv78** [comment]
Either don't set the position of the stream at all before parenting it or set it to the parent's position in the same tick if you want that normal behavior

**Comment by RanchTheDeer** [comment]
I'm not using `setPos` at all in my code, as it should not be required when setting the parent of the stream. Simply setting the parent and then starting the stream should be sufficient to set the correct origin.

**Comment by Vurv78** [comment]
Could you give a code snippet or something? And are you on singleplayer? Cause I still haven't debugged any behaviors on singleplayer

**Comment by RanchTheDeer** [comment]
````if(webAudioCanCreate(S))
        {
            TimeIncrement = 1000
            PlaybackRate = 1
            WebAudio = webAudio(S)
            WebAudio:setParent(TargetEntity)
            WebAudio:setRadius(2000)
            WebAudio:play()
            WebAudio:setVolume(Volume)
            WebAudio:setPlaybackRate(PlaybackRate)
            WebAudio:update()
            timer("playNext_1", 100)
        }
```
I'm running on singleplayer, yes.
I'd really expect SetParent to set the parent position to the center of the entity it's parented to, and for `setPos` to be optional rather than required. Perhaps some clarification is required in the documentation if this is not the case.

**Comment by Vurv78** [comment]
It's not required, I said ``don't set the position of the stream at all before parenting it`` in my last message

**Comment by Vurv78** [comment]
Ok it's meant to not be required but apparently the code wasn't working my bad, didn't notice I had a setPos in there that basically set it to the same position at the prop to parent to. brilliant

**Comment by Vurv78** [comment]
Ugh, it was because at some point I made self.pos initialize as Vector() instead of nil as it initially was meant to be. Documented it so I don't make the mistake again

**Comment by Vurv78** [comment]
Thanks for the report, think it's all good now

**Comment by RanchTheDeer** [comment]
Current revision of code now behaves as expected; parenting the stream now works as expected.

**Pull request merged**
