### PR TITLE
Add api.onedrive.com to webaudio default whitelist

### PR DESCRIPTION
**Pull request by yingKatsu**
Another way to have direct links to onedrive content that pac users often use.

Example link:
https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBcmFSdWJSdXY0SlM5azRMN3F4T1R6YkNYRkd0P2U9a093U3Az/root/content

Pac3 documentation containing a convenient converter for onedrive indirect links to api.onedrive.com direct links:
https://wiki.pac3.info/tutorial/hosting

### CODE REVIEW

**Comment by yogwoggf** [comment]
Courtesy note: @Vurv78 is no longer active so you may want to ping/ask someone with write access to the repository for this PR to get merged

**Comment by yingKatsu** [comment]
> Courtesy note: @Vurv78 is no longer actively maintaining webaudio so you may want to ping/ask someone with write access to the repository for this PR to get merged

Thank you for your consideration; I was aware that he had left Garry's Mod but while doing this same pr to Starfall and looking into webaudio I noticed that they had recently commented a day ago on a wiremod pr so I thought that maybe there was a chance. Would you happen to know anyone with write access that I could ping, or is webaudio now actively maintained by someone else under a different repo?

**Comment by yogwoggf** [comment]
> > Courtesy note: @Vurv78 is no longer actively maintaining webaudio so you may want to ping/ask someone with write access to the repository for this PR to get merged
> 
> Thank you for your consideration; I was aware that he had left Garry's Mod but while doing this same pr to Starfall and looking into webaudio I noticed that they had recently commented a day ago on a wiremod pr so I thought that maybe there was a chance. Would you happen to know anyone with write access that I could ping, or is webaudio now actively maintained by someone else under a different repo?

Makes sense, I just saw the review comment you were talking about. Anyways, I'm not totally sure, but potentially @StyledStrike could have write access?

**Comment by Vurv78** [comment]
I will not do anything that involves me ingame, but if people want to make PRs to my repos I will briefly review and merge if it's fine.

**Comment by StyledStrike** [comment]
> Makes sense, I just saw the review comment you were talking about. Anyways, I'm not totally sure, but potentially @StyledStrike could have write access?

oh I did only two small pull requests here, I'm not a maintainer

**Pull request merged**
